"""alter table book add column key

Revision ID: 3cd543691117
Revises: 6be9784d1d86
Create Date: 2023-11-19 18:41:00.031441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd543691117'
down_revision = '6be9784d1d86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'key')
    # ### end Alembic commands ###
